"""Added new column

Revision ID: 1d00d26e97a2
Revises: 2f750681dea8
Create Date: 2025-06-02 12:30:25.816207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d00d26e97a2'
down_revision = '2f750681dea8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registration_login', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registration_login', schema=None) as batch_op:
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###
